"""unique_email

Revision ID: 53f80eca6382
Revises: a1b56baff61b
Create Date: 2026-01-22 17:19:10.851756

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53f80eca6382"
down_revision: Union[str, Sequence[str], None] = "a1b56baff61b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_unique_email', "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_unique_email', "users", type_="unique")
    # ### end Alembic commands ###
