"""empty message

Revision ID: 9b759d1aa478
Revises: 96c9a63e5f7b
Create Date: 2026-02-28 16:06:43.135727

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b759d1aa478"
down_revision: Union[str, Sequence[str], None] = "96c9a63e5f7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_changes",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("workspace_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("change", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("workspace_id", "workspace_version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_changes")
    # ### end Alembic commands ###
