from dotenv import find_dotenv
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    DB_HOST: str = ...
    DB_PORT: int = ...
    DB_USER: str = ...
    DB_PASSWORD: str = ...
    DB_NAME: str = ...
    JWT_SECRET_KEY: str = ...
    JWT_ALGORITHM: str = ...
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES: int = ...
    JWT_REFRESH_TOKEN_EXPIRE_MINUTES: int = ...
    JWT_REFRESH_COOKIE_NAME: str = ...
    JWT_REFRESH_COOKIE_SECURE: bool = ...
    JWT_REFRESH_COOKIE_SAMESITE: str = ...
    VERIFY_EMAIL_EXPIRE_SECONDS: int = ...
    VERIFY_EMAIL_COOKIE_NAME: str = ...
    VERIFY_EMAIL_COOKIE_SAMESITE: str = ...
    VERIFY_ATTEMPTS: int = ...

    @property
    def database_url(self) -> str:
        return f'postgresql+asyncpg://{self.DB_USER}:{self.DB_PASSWORD}@{self.DB_HOST}:{self.DB_PORT}/{self.DB_NAME}'

    model_config = SettingsConfigDict(
        env_file=find_dotenv(),
        extra='ignore',
    )


settings = Settings()
